### ISSUE TITLE
Reported content hidden only from visitors, not from members

### ISSUE THREAD

**Issue by alanlacerda** [iversia/xenforo-hide-reported-content#1]
I'm not sure if it's the intended behavior of this add-on, but so far I haven't found a way to hide reported content from members, only from unregistered visitors.
For members, only a small message appears on the top of the reported post, saying that the post has been submitted to approval by the moderators, but the content is still visible anyway.

Am I missing something?

**Comment by iversia** [comment]
It's been a while since I touched this one, but I believe once it hits the threshold, it turns reported posts and reported profile posts message states to "moderated."

> This message is awaiting moderator approval, and is invisible to normal visitors.

So unless you have moderator/administrator privileges, the content should be hidden to regular users and visitors. That said, I don't think I ever got around to adding threads/thread titles to the moderator threshold, so it's possible that that some content could still be visible if that's what's being reported.

To delete the content from view completely (so mods/admins cannot see), you still need to act on the reported content in the reported items queue.

**Comment by alanlacerda** [comment]
Thank you for your quick reply!

I think you're right, there's something wrong with my users privileges. They are seeing the reported posts exactly as moderators/administrators. I'll try to determine what is wrong here.
